### PR TITLE
Allow passing exit parameters to run before the servers are terminated

### PR DESCRIPTION
**Pull request by Vice93**
I friend wanted the option to pass his own parameters before stopping the windows service without having to manually open the client and type them. This PR changes the Client to support any amount of arguments to run (e.g. -stop) before shutting down the processes. 

One would still need to stop/restart the Windows Service to get it back up and running after, but you can solve this rather easily with a .bat script.

Not sure if it's something you want, but figured I'd open this PR in case you want to take a look. :)

### CODE REVIEW

**Comment by ravetroll** [comment]
@Vice93 This looks useful, thanks for your contribution.  @brunofvalli as the writer of the client do you have any opinions on this change?  @Vice93 could you split out the classes into their own files for each class?

**Comment by brunofvalli** [comment]
@Vice93 thank you for your contribution and cleaning up of my messy code :+1: 
@ravetroll I am glad you asked my opinion. I don't mind the change at all. This is a nice improvement that I will use on my install :+1: You can go ahead and accept the pull request.

**Comment by Vice93** [comment]
@ravetroll I separated the classes and added some comments. I realized by writing the comments that passing -params doesn't stop the bedrock server process unless you supply "-stop" etc. But it allows you to write scripts to pass any parameters you want, and it closes the client cmd window after. 

Not sure if we should actually force quit, or keep it as is for now. I think it's nice to be able to automate sending other commands as well. 

I renamed the method instead to make it clearer what it does.

**Comment by ravetroll** [comment]
@Vice93 Thanks for merging this in.  Could you expand the wiki and explain how to use your new addition?

**Pull request merged**
