### PR TITLE
Adding Client Console

### PR DESCRIPTION
**Pull request by brunofvalli**
I have added a new project to be a Console for the service.
After the service has been started you can launch the client on the same machine as the server and it will connect to the service via WCF.
This console will display a mirror image of what the Minecraft server displays.
Also you can issue commands as you would in the normal Minecraft console.

Features:
+Issue commands as you would on the Minecraft server
+Get the response as you would on the Minecraft server
+Recovery if the service is stopped the client will wait to reconnect

Known issues/features:
+If you close the client you will not see any old messages from the console already displayed.

### CODE REVIEW

**Comment by brunofvalli** [comment]
Since this is my first pull request let me know if you would like for me to change anything. I know you gave me the control over the repo, but I think it is best for me to go through the pull request process.
Let me know if you would like for me to continue to do this.

**Comment by brunofvalli** [comment]
BTW let me know if you would like me to update the documentation to explain about this new client.

**Review by ravetroll — COMMENTED** [review]
Looks good Bruno.  Could you perhaps make the WCF port configurable rather than hardcoded.  In case of running multiple servers how does it send the commands to the right server?

**Comment by brunofvalli** [comment]
I will add configuration to the port on the server and client side.
I want to just put on record that this current implementation has 0 security. So in its current form we should not allow address configuration. I would hate for people to open this to the internet.

**Comment by brunofvalli** [comment]
Ran into a little of a snag, since the configuration file on the server can accept multiple port numbers I need to have the client only connect to one port number at a time. So during the start up of the client the port number will be requested. And the default of 19134 will be given. But the user will need to know what port number they want to use. 

I think that is the only way. Or the alternative would be to spam a window per found port number in a configuration file.

**Comment by ravetroll** [comment]
Perhaps add port config for the client into the config file so user can specify which ports each server is listening on?

**Comment by brunofvalli** [comment]
Got the new update.
I copied the configuration layout from server to the client. Now adding these
```
<ServerConfig>
    <WCFPortNumber>19134</WCFPortNumber>
</ServerConfig>
```
will create a new command line per port number.

Let me know if you need anything else. :)

**Comment by brunofvalli** [comment]
Just as a side note, this is the first time I have done a pull request for something outside work :)

**Comment by ravetroll** [comment]
I didn't even know what a pull request was, but now I do, that that all went well.  I don't even play minecraft, and yet here I am making Minecraft software with you.

**Comment by brunofvalli** [comment]
omg that is hilarious. I don't play Minecraft too much anymore, but needed a Minecraft server and was writing a service creation software when decided to check if someone had created one, that is when I found this project. Just needed a way to add peopled to the whitelist while the service was running, that is when decided to improve on what you have done. The backup feature is a pretty nice add :)

**Pull request merged**
